"""Documented event schema-bound Pydantic models."""

from .dispatcher import EVENT_DISPATCHER_SERVICE, EventDispatcher
from .models import (
    DeliveryCompletedEvent,
    DeliveryFailedEvent,
    DeliveryStartedEvent,
    EVENT_MODEL_BY_SCHEMA_NAME,
    FileDetectedEvent,
    FileQuarantinedEvent,
    FileStableEvent,
    FileValidatedEvent,
    JobCompletedEvent,
    JobFailedEvent,
    JobRegisteredEvent,
    JobStateChangedEvent,
    ProcessingCompletedEvent,
    ProcessingFailedEvent,
    ProcessingStartedEvent,
    RetryScheduledEvent,
)
from .outbox import (
    DEAD_LETTER_STREAM_NAME,
    LIFECYCLE_STREAM_NAME,
    build_idempotency_key,
    enqueue_event,
    event_model_for_type,
    list_event_summaries,
    validate_event_payload,
)
from .redis_streams import REDIS_STREAM_PAYLOAD_FIELD, RedisPublishResult, RedisStreamClient

__all__ = [
    "build_idempotency_key",
    "DEAD_LETTER_STREAM_NAME",
    "DeliveryCompletedEvent",
    "DeliveryFailedEvent",
    "DeliveryStartedEvent",
    "EVENT_DISPATCHER_SERVICE",
    "EVENT_MODEL_BY_SCHEMA_NAME",
    "enqueue_event",
    "event_model_for_type",
    "EventDispatcher",
    "FileDetectedEvent",
    "FileQuarantinedEvent",
    "FileStableEvent",
    "FileValidatedEvent",
    "JobCompletedEvent",
    "JobFailedEvent",
    "JobRegisteredEvent",
    "JobStateChangedEvent",
    "LIFECYCLE_STREAM_NAME",
    "list_event_summaries",
    "ProcessingCompletedEvent",
    "ProcessingFailedEvent",
    "ProcessingStartedEvent",
    "REDIS_STREAM_PAYLOAD_FIELD",
    "RedisPublishResult",
    "RedisStreamClient",
    "RetryScheduledEvent",
    "validate_event_payload",
]
