#!/usr/bin/env python3
"""Validate Stream Lite schema examples against their JSON Schemas.

This is a verification utility, not runtime implementation code. It requires the
`jsonschema` development dependency declared in `requirements-dev.txt`.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

try:
    from jsonschema import Draft202012Validator, FormatChecker
    from jsonschema.exceptions import ValidationError
except Exception as exc:  # pragma: no cover - exercised only when deps missing
    print(
        "ERROR: missing development dependency `jsonschema`. "
        "Install with `pip install -r requirements-dev.txt`.",
        file=sys.stderr,
    )
    raise SystemExit(2) from exc


FAMILIES = ("api", "events", "artifacts")


@dataclass(frozen=True)
class ValidationResult:
    family: str
    schema_name: str
    example_path: Path
    expected_valid: bool
    passed: bool
    detail: str


def load_json(path: Path):
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def schema_name_from_example(path: Path) -> str:
    """Return schema stem from `name.valid.json` or `name.invalid_enum.json`."""
    parts = path.name.split(".")
    if len(parts) < 3 or parts[-1] != "json":
        raise ValueError(f"example file does not follow <schema>.<case>.json naming: {path}")
    return parts[0]


def expected_valid_from_example(path: Path) -> bool:
    case_name = path.name.split(".")[1]
    if case_name == "valid":
        return True
    if case_name.startswith("invalid"):
        return False
    raise ValueError(f"example file case must be valid or invalid*: {path}")


def iter_examples(root: Path, family: str) -> Iterable[Path]:
    example_dir = root / "schemas" / "examples" / family
    if not example_dir.exists():
        return []
    return sorted(example_dir.glob("*.json"))


def validate_one(root: Path, family: str, example_path: Path) -> ValidationResult:
    schema_stem = schema_name_from_example(example_path)
    expected_valid = expected_valid_from_example(example_path)
    schema_path = root / "schemas" / family / f"{schema_stem}.schema.json"
    if not schema_path.exists():
        return ValidationResult(
            family=family,
            schema_name=schema_stem,
            example_path=example_path,
            expected_valid=expected_valid,
            passed=False,
            detail=f"schema file not found: {schema_path}",
        )

    schema = load_json(schema_path)
    example = load_json(example_path)
    validator = Draft202012Validator(schema, format_checker=FormatChecker())
    try:
        validator.validate(example)
        is_valid = True
        detail = "valid"
    except ValidationError as exc:
        is_valid = False
        path = "/".join(str(part) for part in exc.absolute_path) or "<root>"
        detail = f"invalid at {path}: {exc.message}"

    passed = is_valid if expected_valid else not is_valid
    if not passed and expected_valid:
        detail = f"expected valid but validation failed: {detail}"
    elif not passed and not expected_valid:
        detail = "expected invalid but validation succeeded"
    return ValidationResult(
        family=family,
        schema_name=schema_stem,
        example_path=example_path,
        expected_valid=expected_valid,
        passed=passed,
        detail=detail,
    )


def validate_all(root: Path) -> list[ValidationResult]:
    results: list[ValidationResult] = []
    for family in FAMILIES:
        for example_path in iter_examples(root, family):
            results.append(validate_one(root, family, example_path))
    return results


def render_report(root: Path, results: list[ValidationResult]) -> str:
    total = len(results)
    failures = [result for result in results if not result.passed]
    lines = [
        "# JSON Schema Fixture Validation Evidence",
        "",
        "Generated by `tools/validate_schema_examples.py`.",
        "",
        "## Summary",
        "",
        "| Check | Count |",
        "|---|---:|",
        f"| Examples validated | {total} |",
        f"| Passed | {total - len(failures)} |",
        f"| Failed | {len(failures)} |",
        "",
    ]
    if failures:
        lines += ["## Failures", "", "| Family | Example | Detail |", "|---|---|---|"]
        for result in failures:
            rel = result.example_path.relative_to(root)
            lines.append(f"| {result.family} | `{rel}` | {result.detail} |")
    else:
        lines += ["## Result", "", "All valid examples passed and all invalid examples failed as expected."]
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".", help="Repository root; default current directory")
    parser.add_argument("--write-evidence", action="store_true", help="Write Markdown evidence under docs/verification/evidence")
    parser.add_argument("--evidence-path", default="docs/verification/evidence/schema_fixture_validation.md")
    args = parser.parse_args(argv)

    root = Path(args.root).resolve()
    results = validate_all(root)
    report = render_report(root, results)
    failures = [result for result in results if not result.passed]

    if args.write_evidence:
        evidence_path = root / args.evidence_path
        evidence_path.parent.mkdir(parents=True, exist_ok=True)
        evidence_path.write_text(report, encoding="utf-8")

    print(report)
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
